=== pratikdhage007/car-store-app-2016/src/main/webapp/xsd/cars.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.soap.com/cars" 
xmlns:tns="http://www.soap.com/cars" elementFormDefault="qualified">

	<!-- global element -->
	<element name="cars" type="tns:carlist"></element>
	
	<complexType name="carlist">
		<sequence>
			<element name="car" type="tns:thecar" minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	
	<complexType name="thecar">
		<sequence>
			<element name="cid" type="int" minOccurs="1" maxOccurs="1"></element>
			<element name="name" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="price" type="int" minOccurs="1" maxOccurs="1"></element>
			<element name="transmission" type="string" minOccurs="1" maxOccurs="1"></element>
		    <element name="warranty" type="int" minOccurs="1" maxOccurs="1"></element>
		    <element name="image" type="base64Binary" minOccurs="0" maxOccurs="1"></element>
		    <element name="horsepower" type="string" minOccurs="1" maxOccurs="1"></element>	 
		</sequence>
	</complexType>

</schema>

=== pratikdhage007/car-store-app-2016/src/main/webapp/xsd/cars.xml
<?xml version="1.0" encoding="UTF-8"?>
<cars xmlns="http://www.soap.com/cars" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.soap.com/cars cars.xsd">
	<car>
		<cid>009</cid>
		<name>Chrysler 300</name>
		<price>45000</price>
		<transmission>6-Speed Auto</transmission>
		<warranty>3</warranty>
		<horsepower>400bhp @ 1200</horsepower>
	</car>

	<car>
		<cid>333</cid>
		<name>Dodge Charger</name>
		<price>40000</price>
		<transmission>6-Speed Auto</transmission>
		<warranty>2</warranty>
		<horsepower>400bhp @ 1500</horsepower>
	</car>

</cars>

=== pratikdhage007/car-store-app-2016/src/main/webapp/xsd/cars1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:cars xmlns:tns="http://www.soap.com/cars" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.soap.com/cars cars.xsd ">
  <tns:car>
	    <tns:cid>0</tns:cid>
	    <tns:name>tns:name</tns:name>
	    <tns:price>0</tns:price>
	    <tns:transmission>tns:transmission</tns:transmission>
	    <tns:warranty>0</tns:warranty>
	    <tns:horsepower>tns:horsepower</tns:horsepower>
  </tns:car>

</tns:cars>
